set nocompatible
"filetype plugin indent on    " required

set number
set ruler
syntax on
set autoindent
set smartindent
set encoding=utf-8
set t_Co=256
set background=dark
set hlsearch
set colorcolumn=80
set mouse=a

set tabstop=4
set shiftwidth=4
set noexpandtab
set cindent

" Tab navigation like Firefox.
nnoremap <S-Tab> :tabprevious<CR>
nnoremap <Tab>   :tabnext<CR>
nnoremap <C-t>   :tabnew<CR>

"split navigations
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

map <C-n> :Explore<CR>

set noshowmode

function! GetMode()
	let m = mode()
	if m=='i'
		return 'Insert'
	elseif m=='n'
		return 'Normal'
	elseif m=='R'
		return 'Replace'
	elseif m==?'c'
		return 'Command'
	else
		return 'Visual'
	endif
endfunction

set laststatus=2
set statusline=
set statusline+=%5*\ %{GetMode()}
set statusline+=\ %1*\ \[%n]							"Buffernumber
set statusline+=\ %2*\ %<%f								"Filepath
set statusline+=%m										"modified flag
set statusline+=\ %3*%=									"Space
set statusline+=%{''.(&fenc!=''?&fenc:&enc).''}\ \|		"Encoding
set statusline+=\ %{&ff}\ \|							"Encoding2
set statusline+=\ %{&expandtab?'spaces':'tabs'}\ \|		"Check use of spaces or tabs
set statusline+=\ %Y									"Filetype
set statusline+=\ %4*\ %c:%l/%L							"Col:line/numlines
set statusline+=\ 										"Blank space at the end

hi User1 ctermbg=Blue
hi User2 ctermbg=Green ctermfg=Black
hi User3 ctermbg=Black
hi User4 ctermbg=Magenta ctermfg=Black

"let base16colorspace = 256

au BufNewFile,BufRead *.py
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    \ set textwidth=80 |
    \ set expandtab |
    \ set autoindent |
    \ set fileformat=unix
