title: Pablo Hernández
email: pabloheralm@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my Github page and blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: pablololo12
github_username:  pablololo12

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate